In [ ]:
import polars as pl
from pathlib import Path

# Load the CSV (all columns as Utf8 to avoid inference issues)

csv_path = Path("../data/raw/lcdv2/hourly/2024/72034354852-2024.csv")

df = pl.read_csv(
    csv_path,
    infer_schema_length=0,   # force all Utf8
    schema_overrides={"DATE": pl.Utf8, "STATION": pl.Utf8}
)

df.head()

shape: (5, 125)
┌───────────┬───────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ STATION   ┆ DATE      ┆ LATITUDE ┆ LONGITUDE ┆ … ┆ BackupLat ┆ BackupLon ┆ BackupNam ┆ WindEquip │
│ ---       ┆ ---       ┆ ---      ┆ ---       ┆   ┆ itude     ┆ gitude    ┆ e         ┆ mentChang │
│ str       ┆ str       ┆ str      ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ eDate     │
│           ┆           ┆          ┆           ┆   ┆ str       ┆ str       ┆ str       ┆ ---       │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆ str       │
╞═══════════╪═══════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 720343548 ┆ 2024-01-0 ┆ 44.33333 ┆ -89.01972 ┆ … ┆           ┆           ┆           ┆           │
│ 52        ┆ 1T00:15:0 ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│           ┆ 0         ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ 720343548 ┆ 2024-01-0 ┆ 44.33333 ┆ -89.01972 ┆ … ┆           ┆           ┆           ┆           │
│ 52        ┆ 1T00:35:0 ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│           ┆ 0         ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ 720343548 ┆ 2024-01-0 ┆ 44.33333 ┆ -89.01972 ┆ … ┆           ┆           ┆           ┆           │
│ 52        ┆ 1T00:55:0 ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│           ┆ 0         ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ 720343548 ┆ 2024-01-0 ┆ 44.33333 ┆ -89.01972 ┆ … ┆           ┆           ┆           ┆           │
│ 52        ┆ 1T01:15:0 ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│           ┆ 0         ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ 720343548 ┆ 2024-01-0 ┆ 44.33333 ┆ -89.01972 ┆ … ┆           ┆           ┆           ┆           │
│ 52        ┆ 1T01:35:0 ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│           ┆ 0         ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
└───────────┴───────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [2]:
cols = df.columns

daily_fields = [c for c in df.columns if c.startswith("Daily")]
daily_fields

['DailyAverageDewPointTemperature',
 'DailyAverageDryBulbTemperature',
 'DailyAverageRelativeHumidity',
 'DailyAverageSeaLevelPressure',
 'DailyAverageStationPressure',
 'DailyAverageWetBulbTemperature',
 'DailyAverageWindSpeed',
 'DailyCoolingDegreeDays',
 'DailyDepartureFromNormalAverageTemperature',
 'DailyHeatingDegreeDays',
 'DailyMaximumDryBulbTemperature',
 'DailyMinimumDryBulbTemperature',
 'DailyPeakWindDirection',
 'DailyPeakWindSpeed',
 'DailyPrecipitation',
 'DailySnowDepth',
 'DailySnowfall',
 'DailySustainedWindDirection',
 'DailySustainedWindSpeed',
 'DailyWeather']

In [ ]:
# Convert DATE to a datetime type & some date component fields for grouping/sorting
df = (
    df
    .with_columns([
        pl.col("DATE").str.strptime(pl.Datetime, strict=False).alias("dt"),
    ])
    .with_columns([
        pl.col("dt").dt.date().alias("date"),
        pl.col("dt").dt.month().alias("month"),
    ])
)

df.select(["DATE", "dt", "date", "month"]).head()

shape: (5, 4)
┌─────────────────────┬─────────────────────┬────────────┬───────┐
│ DATE                ┆ dt                  ┆ date       ┆ month │
│ ---                 ┆ ---                 ┆ ---        ┆ ---   │
│ str                 ┆ datetime[μs]        ┆ date       ┆ i8    │
╞═════════════════════╪═════════════════════╪════════════╪═══════╡
│ 2024-01-01T00:15:00 ┆ 2024-01-01 00:15:00 ┆ 2024-01-01 ┆ 1     │
│ 2024-01-01T00:35:00 ┆ 2024-01-01 00:35:00 ┆ 2024-01-01 ┆ 1     │
│ 2024-01-01T00:55:00 ┆ 2024-01-01 00:55:00 ┆ 2024-01-01 ┆ 1     │
│ 2024-01-01T01:15:00 ┆ 2024-01-01 01:15:00 ┆ 2024-01-01 ┆ 1     │
│ 2024-01-01T01:35:00 ┆ 2024-01-01 01:35:00 ┆ 2024-01-01 ┆ 1     │
└─────────────────────┴─────────────────────┴────────────┴───────┘

In [4]:
# Boolean: does this row have ANY populated daily field?
df = df.with_columns(
    pl.any_horizontal([pl.col(f) != "" for f in daily_fields]).alias("has_daily_values")
)

df.select(["DATE", "has_daily_values"] + daily_fields).head()

shape: (5, 22)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ DATE      ┆ has_daily ┆ DailyAver ┆ DailyAver ┆ … ┆ DailySnow ┆ DailySust ┆ DailySust ┆ DailyWea │
│ ---       ┆ _values   ┆ ageDewPoi ┆ ageDryBul ┆   ┆ fall      ┆ ainedWind ┆ ainedWind ┆ ther     │
│ str       ┆ ---       ┆ ntTempera ┆ bTemperat ┆   ┆ ---       ┆ Direction ┆ Speed     ┆ ---      │
│           ┆ bool      ┆ tur…      ┆ ure       ┆   ┆ str       ┆ ---       ┆ ---       ┆ str      │
│           ┆           ┆ ---       ┆ ---       ┆   ┆           ┆ str       ┆ str       ┆          │
│           ┆           ┆ str       ┆ str       ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2024-01-0 ┆ false     ┆           ┆           ┆ … ┆           ┆           ┆           ┆          │
│ 1T00:15:0 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 0         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2024-01-0 ┆ false     ┆           ┆           ┆ … ┆           ┆           ┆           ┆          │
│ 1T00:35:0 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 0         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2024-01-0 ┆ false     ┆           ┆           ┆ … ┆           ┆           ┆           ┆          │
│ 1T00:55:0 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 0         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2024-01-0 ┆ false     ┆           ┆           ┆ … ┆           ┆           ┆           ┆          │
│ 1T01:15:0 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 0         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2024-01-0 ┆ false     ┆           ┆           ┆ … ┆           ┆           ┆           ┆          │
│ 1T01:35:0 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 0         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [ ]:
# Count rows per day that contain daily field values
daily_counts = (
    df.group_by("date")
      .agg(pl.col("has_daily_values").sum().alias("daily_rows_with_values"))
      .sort("date")
)

daily_counts

shape: (366, 2)
┌────────────┬────────────────────────┐
│ date       ┆ daily_rows_with_values │
│ ---        ┆ ---                    │
│ date       ┆ u32                    │
╞════════════╪════════════════════════╡
│ 2024-01-01 ┆ 0                      │
│ 2024-01-02 ┆ 0                      │
│ 2024-01-03 ┆ 1                      │
│ 2024-01-04 ┆ 0                      │
│ 2024-01-05 ┆ 0                      │
│ …          ┆ …                      │
│ 2024-12-27 ┆ 1                      │
│ 2024-12-28 ┆ 1                      │
│ 2024-12-29 ┆ 1                      │
│ 2024-12-30 ┆ 1                      │
│ 2024-12-31 ┆ 0                      │
└────────────┴────────────────────────┘

In [ ]:
# Days with no daily value entries
days_with_zero = daily_counts.filter(pl.col("daily_rows_with_values") == 0)
days_with_zero

shape: (266, 2)
┌────────────┬────────────────────────┐
│ date       ┆ daily_rows_with_values │
│ ---        ┆ ---                    │
│ date       ┆ u32                    │
╞════════════╪════════════════════════╡
│ 2024-01-01 ┆ 0                      │
│ 2024-01-02 ┆ 0                      │
│ 2024-01-04 ┆ 0                      │
│ 2024-01-05 ┆ 0                      │
│ 2024-01-14 ┆ 0                      │
│ …          ┆ …                      │
│ 2024-12-17 ┆ 0                      │
│ 2024-12-18 ┆ 0                      │
│ 2024-12-21 ┆ 0                      │
│ 2024-12-22 ┆ 0                      │
│ 2024-12-31 ┆ 0                      │
└────────────┴────────────────────────┘

In [8]:
# Days with rows containing daily values > 1
days_with_multiple = daily_counts.filter(pl.col("daily_rows_with_values") > 1)
days_with_multiple

shape: (0, 2)
┌──────┬────────────────────────┐
│ date ┆ daily_rows_with_values │
│ ---  ┆ ---                    │
│ date ┆ u32                    │
╞══════╪════════════════════════╡
└──────┴────────────────────────┘

Appears as though daily values are only entered once per day at maximum, but are not reliably entered once per day.

Will check the consistency and quality of hourly fields.

In [9]:
# Check for duplicate timestamps
dupes = (
    df.group_by("dt")
      .agg(pl.len().alias("count"))
      .filter(pl.col("count") > 1)
)

dupes

shape: (0, 2)
┌──────────────┬───────┐
│ dt           ┆ count │
│ ---          ┆ ---   │
│ datetime[μs] ┆ u32   │
╞══════════════╪═══════╡
└──────────────┴───────┘

In [10]:
# Checking for time interval consistency
df_sorted = df.sort("dt")

df_gaps = (
    df_sorted
    .with_columns(
        pl.col("dt").diff().alias("delta")
    )
    .select(["DATE", "dt", "delta"])
)

df_gaps.head(20)

shape: (20, 3)
┌─────────────────────┬─────────────────────┬──────────────┐
│ DATE                ┆ dt                  ┆ delta        │
│ ---                 ┆ ---                 ┆ ---          │
│ str                 ┆ datetime[μs]        ┆ duration[μs] │
╞═════════════════════╪═════════════════════╪══════════════╡
│ 2024-01-01T00:15:00 ┆ 2024-01-01 00:15:00 ┆ null         │
│ 2024-01-01T00:35:00 ┆ 2024-01-01 00:35:00 ┆ 20m          │
│ 2024-01-01T00:55:00 ┆ 2024-01-01 00:55:00 ┆ 20m          │
│ 2024-01-01T01:15:00 ┆ 2024-01-01 01:15:00 ┆ 20m          │
│ 2024-01-01T01:35:00 ┆ 2024-01-01 01:35:00 ┆ 20m          │
│ …                   ┆ …                   ┆ …            │
│ 2024-01-01T05:15:00 ┆ 2024-01-01 05:15:00 ┆ 20m          │
│ 2024-01-01T05:35:00 ┆ 2024-01-01 05:35:00 ┆ 20m          │
│ 2024-01-01T05:55:00 ┆ 2024-01-01 05:55:00 ┆ 20m          │
│ 2024-01-01T06:15:00 ┆ 2024-01-01 06:15:00 ┆ 20m          │
│ 2024-01-01T06:35:00 ┆ 2024-01-01 06:35:00 ┆ 20m          │
└─────────────────────┴─────────────────────┴──────────────┘

In [11]:
# Looks consistent at a glance, checking for large gaps
large_gaps = df_gaps.filter(pl.col("delta") > pl.duration(hours=2))
large_gaps

shape: (17, 3)
┌─────────────────────┬─────────────────────┬──────────────┐
│ DATE                ┆ dt                  ┆ delta        │
│ ---                 ┆ ---                 ┆ ---          │
│ str                 ┆ datetime[μs]        ┆ duration[μs] │
╞═════════════════════╪═════════════════════╪══════════════╡
│ 2024-01-14T10:15:00 ┆ 2024-01-14 10:15:00 ┆ 7h 40m       │
│ 2024-02-09T07:10:00 ┆ 2024-02-09 07:10:00 ┆ 7h 11m       │
│ 2024-03-06T07:15:00 ┆ 2024-03-06 07:15:00 ┆ 6h 40m       │
│ 2024-03-21T16:55:00 ┆ 2024-03-21 16:55:00 ┆ 3h 20m       │
│ 2024-04-30T20:35:00 ┆ 2024-04-30 20:35:00 ┆ 4h           │
│ …                   ┆ …                   ┆ …            │
│ 2024-11-30T22:15:00 ┆ 2024-11-30 22:15:00 ┆ 6h 40m       │
│ 2024-12-01T15:55:00 ┆ 2024-12-01 15:55:00 ┆ 15h 56m      │
│ 2024-12-03T15:35:00 ┆ 2024-12-03 15:35:00 ┆ 4h 20m       │
│ 2024-12-05T11:35:00 ┆ 2024-12-05 11:35:00 ┆ 11h 36m      │
│ 2024-12-18T08:15:00 ┆ 2024-12-18 08:15:00 ┆ 6h           │
└─────────────────────┴─────────────────────┴──────────────┘

In [13]:
summary = {
    "days_with_zero_daily_rows": days_with_zero.height,
    "days_with_multiple_daily_rows": days_with_multiple.height,
    "duplicate_timestamps": dupes.height,
    "large_gaps": large_gaps.height,
}

summary

{'days_with_zero_daily_rows': 266,
 'days_with_multiple_daily_rows': 0,
 'duplicate_timestamps': 0,
 'large_gaps': 17}

Daily data is unacceptabel, hourly data is seemingly acceptable. Repeating with one more station sample.

In [ ]:

csv_path = Path("../data/raw/lcdv2/daily/2025/72662604864-2025.csv")

df = pl.read_csv(
    csv_path,
    infer_schema_length=0,   # force all Utf8
    schema_overrides={"DATE": pl.Utf8, "STATION": pl.Utf8}
)

# Convert DATE to a datetime type & some date component fields for grouping/sorting
df = (
    df
    .with_columns([
        pl.col("DATE").str.strptime(pl.Datetime, strict=False).alias("dt"),
    ])
    .with_columns([
        pl.col("dt").dt.date().alias("date"),
        pl.col("dt").dt.month().alias("month"),
    ])
)

cols = df.columns

daily_fields = [c for c in df.columns if c.startswith("Daily")]

df = df.with_columns(
    pl.any_horizontal([pl.col(f) != "" for f in daily_fields]).alias("has_daily_values")
)

daily_counts = (
    df.group_by("date")
      .agg(pl.col("has_daily_values").sum().alias("daily_rows_with_values"))
      .sort("date")
)

daily_counts

shape: (237, 2)
┌────────────┬────────────────────────┐
│ date       ┆ daily_rows_with_values │
│ ---        ┆ ---                    │
│ date       ┆ u32                    │
╞════════════╪════════════════════════╡
│ 2025-01-01 ┆ 1                      │
│ 2025-01-02 ┆ 1                      │
│ 2025-01-03 ┆ 1                      │
│ 2025-01-04 ┆ 0                      │
│ 2025-01-05 ┆ 1                      │
│ …          ┆ …                      │
│ 2025-08-21 ┆ 1                      │
│ 2025-08-22 ┆ 1                      │
│ 2025-08-23 ┆ 1                      │
│ 2025-08-24 ┆ 1                      │
│ 2025-08-25 ┆ 0                      │
└────────────┴────────────────────────┘

In [4]:
# Days with no daily value entries
days_with_zero = daily_counts.filter(pl.col("daily_rows_with_values") == 0)
days_with_zero

shape: (22, 2)
┌────────────┬────────────────────────┐
│ date       ┆ daily_rows_with_values │
│ ---        ┆ ---                    │
│ date       ┆ u32                    │
╞════════════╪════════════════════════╡
│ 2025-01-04 ┆ 0                      │
│ 2025-01-09 ┆ 0                      │
│ 2025-01-19 ┆ 0                      │
│ 2025-01-20 ┆ 0                      │
│ 2025-01-21 ┆ 0                      │
│ …          ┆ …                      │
│ 2025-02-23 ┆ 0                      │
│ 2025-02-24 ┆ 0                      │
│ 2025-02-25 ┆ 0                      │
│ 2025-02-26 ┆ 0                      │
│ 2025-08-25 ┆ 0                      │
└────────────┴────────────────────────┘

In [5]:
# Days with rows containing daily values > 1
days_with_multiple = daily_counts.filter(pl.col("daily_rows_with_values") > 1)
days_with_multiple

shape: (0, 2)
┌──────┬────────────────────────┐
│ date ┆ daily_rows_with_values │
│ ---  ┆ ---                    │
│ date ┆ u32                    │
╞══════╪════════════════════════╡
└──────┴────────────────────────┘

In [6]:
# Check for duplicate timestamps
dupes = (
    df.group_by("dt")
      .agg(pl.len().alias("count"))
      .filter(pl.col("count") > 1)
)

dupes

shape: (0, 2)
┌──────────────┬───────┐
│ dt           ┆ count │
│ ---          ┆ ---   │
│ datetime[μs] ┆ u32   │
╞══════════════╪═══════╡
└──────────────┴───────┘

In [7]:
# Checking for time interval consistency
df_sorted = df.sort("dt")

df_gaps = (
    df_sorted
    .with_columns(
        pl.col("dt").diff().alias("delta")
    )
    .select(["DATE", "dt", "delta"])
)

df_gaps.head(20)

shape: (20, 3)
┌─────────────────────┬─────────────────────┬──────────────┐
│ DATE                ┆ dt                  ┆ delta        │
│ ---                 ┆ ---                 ┆ ---          │
│ str                 ┆ datetime[μs]        ┆ duration[μs] │
╞═════════════════════╪═════════════════════╪══════════════╡
│ 2025-01-01T00:15:00 ┆ 2025-01-01 00:15:00 ┆ null         │
│ 2025-01-01T00:35:00 ┆ 2025-01-01 00:35:00 ┆ 20m          │
│ 2025-01-01T00:55:00 ┆ 2025-01-01 00:55:00 ┆ 20m          │
│ 2025-01-01T01:15:00 ┆ 2025-01-01 01:15:00 ┆ 20m          │
│ 2025-01-01T01:35:00 ┆ 2025-01-01 01:35:00 ┆ 20m          │
│ …                   ┆ …                   ┆ …            │
│ 2025-01-01T05:15:00 ┆ 2025-01-01 05:15:00 ┆ 20m          │
│ 2025-01-01T05:35:00 ┆ 2025-01-01 05:35:00 ┆ 20m          │
│ 2025-01-01T05:55:00 ┆ 2025-01-01 05:55:00 ┆ 20m          │
│ 2025-01-01T06:15:00 ┆ 2025-01-01 06:15:00 ┆ 20m          │
│ 2025-01-01T06:35:00 ┆ 2025-01-01 06:35:00 ┆ 20m          │
└─────────────────────┴─────────────────────┴──────────────┘

In [8]:
# Looks consistent at a glance, checking for large gaps
large_gaps = df_gaps.filter(pl.col("delta") > pl.duration(hours=2))
large_gaps

shape: (3, 3)
┌─────────────────────┬─────────────────────┬──────────────┐
│ DATE                ┆ dt                  ┆ delta        │
│ ---                 ┆ ---                 ┆ ---          │
│ str                 ┆ datetime[μs]        ┆ duration[μs] │
╞═════════════════════╪═════════════════════╪══════════════╡
│ 2025-03-04T23:59:00 ┆ 2025-03-04 23:59:00 ┆ 3h 4m        │
│ 2025-03-05T02:55:00 ┆ 2025-03-05 02:55:00 ┆ 2h 56m       │
│ 2025-03-31T11:15:00 ┆ 2025-03-31 11:15:00 ┆ 6h 25m       │
└─────────────────────┴─────────────────────┴──────────────┘

In [9]:
summary = {
    "days_with_zero_daily_rows": days_with_zero.height,
    "days_with_multiple_daily_rows": days_with_multiple.height,
    "duplicate_timestamps": dupes.height,
    "large_gaps": large_gaps.height,
}

summary

{'days_with_zero_daily_rows': 22,
 'days_with_multiple_daily_rows': 0,
 'duplicate_timestamps': 0,
 'large_gaps': 3}